apiVersion: v1
kind: Pod
metadata:
  name: simpleapi
  labels:
    name: simpleapi
spec:
  containers:
  - name: simpleapi
    image: xmartinezzz/simpleapi
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
